models.py
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from flask_bcrypt import Bcrypt


db = SQLAlchemy()
bcrypt = Bcrypt()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    lists = db.relationship("MovieList", backref="author", lazy=True)


class MovieList(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    movies = db.relationship("Movie", backref="list", lazy=True)


class Movie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    year = db.Column(db.String(4), nullable=False)
    imdb_id = db.Column(db.String(100), nullable=False)
    list_id = db.Column(db.Integer, db.ForeignKey("movie_list.id"), nullable=False)

    __table_args__ = (db.UniqueConstraint("imdb_id", "list_id", name="unique_movie"),)

main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class CreateListForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=6)])
    submit = SubmitField("Create List", render_kw={"class": "cssbuttons-io"})

users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from models import User


class RegistrationForm(FlaskForm):
    username = StringField(
        "Username", validators=[DataRequired(), Length(min=2, max=20)]
    )
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    confirm_password = PasswordField(
        "Confirm Password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Sign Up")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                "That username is taken. Please choose a different one."
            )

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("That email is already registered.")


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember = BooleanField("Remember Me")
    submit = SubmitField("Login")

app.py
from flask import Flask
from config import Config
from models import db, User
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_migrate import Migrate

from users.routes import users
from main.routes import main

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)

    login_manager = LoginManager(app)
    login_manager.login_view = "users.login"


    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


    # Register Blueprints
    app.register_blueprint(users)
    app.register_blueprint(main)

    with app.app_context():
        db.create_all()

    return app

main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__, template_folder="templates")

from main import routes

main/routes.py
import random
from flask import render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
import sqlalchemy
from main.forms import CreateListForm
from main.omdb_util import get_movie_detail, list_movies_by_search
from models import db, MovieList, Movie
from main import constants, main


@main.route("/")
@main.route("/home")
@login_required
def home():
    lists = MovieList.query.filter_by(user_id=current_user.id).all()
    form = CreateListForm()

    slides_sample = random.sample(sorted(constants.MOVIE_WALLPAPERS), 4)
    slides = {k: constants.MOVIE_WALLPAPERS[k] for k in slides_sample}
    return render_template("home.html", lists=lists, form=form, movies_slides=slides)


@main.route("/search/<int:list_id>/<int:page>", methods=["POST"])
@login_required
def search(list_id, page=1):
    movie_list = MovieList.query.get_or_404(list_id)
    movies = list_movies_by_search(query=request.form["query"], page=page)
    return render_template(
        "movie_list.html",
        list=movie_list,
        movies=movies,
        curr_page=page,
        prev_query=request.form["query"],
    )


@main.route("/add_movie", methods=["POST"])
@login_required
def add_movie():
    page = int(request.form["page"])
    query = request.form["query"]

    movie_title = request.form["title"]
    movie_year = request.form["year"]
    imdb_id = request.form["imdb_id"]
    list_id = request.form["list_id"]

    movie = Movie(title=movie_title, year=movie_year, imdb_id=imdb_id, list_id=list_id)
    try:
        db.session.add(movie)
        db.session.commit()
        flash("Movie added to the list!", "success")

    except sqlalchemy.exc.IntegrityError:
        db.session.rollback()
        flash("Movie already exists in the list!", "danger")

    movie_list = MovieList.query.get_or_404(list_id)
    movies = list_movies_by_search(query=query, page=page)
    return render_template(
        "movie_list.html",
        list=movie_list,
        movies=movies,
        curr_page=page,
        prev_query=query,
    )


@main.route("/create_list", methods=["POST"])
@login_required
def create_list():
    list_title = request.form["title"]
    movie_list = MovieList(title=list_title, author=current_user)
    db.session.add(movie_list)
    db.session.commit()
    flash("Movie list created!", "success")

    return redirect(url_for("main.home"))


@main.route("/list/<int:list_id>")
@login_required
def view_list(list_id):
    movie_list = MovieList.query.get_or_404(list_id)
    return render_template("movie_list.html", list=movie_list)


@main.route("/movie/<string:imdb_id>")
@login_required
def movie_detail(imdb_id):
    detail = get_movie_detail(imdb_id)
    return render_template("movie_detail.html", detail=detail)


@main.route("/delete_movie/<int:list_id>/<string:imdb_id>", methods=["GET"])
@login_required
def delete_movie(list_id, imdb_id):
    movie = Movie.query.filter_by(list_id=list_id, imdb_id=imdb_id).first()
    if movie:
        db.session.delete(movie)
        db.session.commit()
        flash("Movie deleted from the list!", "success")
    else:
        flash("Movie not found in the list!", "danger")
    return redirect(url_for("main.view_list", list_id=list_id))

users/__init__.py
from flask import Blueprint

users = Blueprint("users", __name__, template_folder="templates")

from users import routes

users/routes.py
from flask import render_template, redirect, url_for, flash
from flask_login import login_user, current_user, logout_user
from models import db, bcrypt, User
from users.forms import RegistrationForm, LoginForm
from users import users


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created!", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for("main.home"))
        else:
            flash("Login Unsuccessful. Please check email and password", "danger")
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Movie Library</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>

<body>
    <nav>
        <p class="app_heading">The Movie Library</p>
        <ul>
            {% if current_user.is_authenticated %}
            <p class="username">Hi,&nbsp;{{ current_user.username }}</p>

            <button class="cssbuttons-io">
                <a href="{{ url_for('main.home') }}">
                    <span>
                        <p>Home</p>
                        <svg viewBox="0 3 19.7 19.7" xmlns="http://www.w3.org/2000/svg" role="img"
                            aria-labelledby="homeIconTitle" class="home-icon">
                            <path d="M12 3l7 6-1 1-1-1V20h-4V14H9v6H5V9L4 10 3 9l9-6z" fill="white" />
                        </svg>
                    </span>
                </a>
            </button>

            <button class="cssbuttons-io">
                <a href="{{ url_for('users.logout') }}">
                    <span>
                        <p>Logout</p>
                        <svg viewBox="0 2 19 20" xmlns="http://www.w3.org/2000/svg" role="img"
                            aria-labelledby="loginIconTitle" class="login-icon">
                            <path fill="white"
                                d="M10.09,15.59L13.67,12L10.09,8.41L11.5,7L16.5,12L11.5,17L10.09,15.59M19,3H5C3.89,3 3,3.89 3,5V19C3,20.11 3.89,21 5,21H19C20.11,21 21,20.11 21,19V5C21,3.89 20.11,3 19,3M19,19H5V5H19V19Z" />
                        </svg>
                    </span>
                </a>
            </button>

            {% else %}
            <li><a href="{{ url_for('users.login') }}">Login</a></li>
            <li><a href="{{ url_for('users.register') }}">Register</a></li>
            {% endif %}
        </ul>
    </nav>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}

    <script>
        alert("{{ message }}")
    </script>

    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
    <!-- 
    <footer>
        &copy; 2024 Movie Library. All rights reserved.
    </footer> -->
</body>

</html>