main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class CreateListForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=6)])
    submit = SubmitField("Create List", render_kw={"class": "cssbuttons-io"})

main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__, template_folder="templates")

from main import routes

main/routes.py
import random
from flask import render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
import sqlalchemy
from main.forms import CreateListForm
from main.omdb_util import get_movie_detail, list_movies_by_search
from models import db, MovieList, Movie
from main import constants, main


@main.route("/")
@main.route("/home")
@login_required
def home():
    lists = MovieList.query.filter_by(user_id=current_user.id).all()
    form = CreateListForm()

    slides_sample = random.sample(sorted(constants.MOVIE_WALLPAPERS), 4)
    slides = {k: constants.MOVIE_WALLPAPERS[k] for k in slides_sample}
    return render_template("home.html", lists=lists, form=form, movies_slides=slides)


@main.route("/search/<int:list_id>/<int:page>", methods=["POST"])
@login_required
def search(list_id, page=1):
    movie_list = MovieList.query.get_or_404(list_id)
    movies = list_movies_by_search(query=request.form["query"], page=page)
    return render_template(
        "movie_list.html",
        list=movie_list,
        movies=movies,
        curr_page=page,
        prev_query=request.form["query"],
    )


@main.route("/add_movie", methods=["POST"])
@login_required
def add_movie():
    page = int(request.form["page"])
    query = request.form["query"]

    movie_title = request.form["title"]
    movie_year = request.form["year"]
    imdb_id = request.form["imdb_id"]
    list_id = request.form["list_id"]

    movie = Movie(title=movie_title, year=movie_year, imdb_id=imdb_id, list_id=list_id)
    try:
        db.session.add(movie)
        db.session.commit()
        flash("Movie added to the list!", "success")

    except sqlalchemy.exc.IntegrityError:
        db.session.rollback()
        flash("Movie already exists in the list!", "danger")

    movie_list = MovieList.query.get_or_404(list_id)
    movies = list_movies_by_search(query=query, page=page)
    return render_template(
        "movie_list.html",
        list=movie_list,
        movies=movies,
        curr_page=page,
        prev_query=query,
    )


@main.route("/create_list", methods=["POST"])
@login_required
def create_list():
    list_title = request.form["title"]
    movie_list = MovieList(title=list_title, author=current_user)
    db.session.add(movie_list)
    db.session.commit()
    flash("Movie list created!", "success")

    return redirect(url_for("main.home"))


@main.route("/list/<int:list_id>")
@login_required
def view_list(list_id):
    movie_list = MovieList.query.get_or_404(list_id)
    return render_template("movie_list.html", list=movie_list)


@main.route("/movie/<string:imdb_id>")
@login_required
def movie_detail(imdb_id):
    detail = get_movie_detail(imdb_id)
    return render_template("movie_detail.html", detail=detail)


@main.route("/delete_movie/<int:list_id>/<string:imdb_id>", methods=["GET"])
@login_required
def delete_movie(list_id, imdb_id):
    movie = Movie.query.filter_by(list_id=list_id, imdb_id=imdb_id).first()
    if movie:
        db.session.delete(movie)
        db.session.commit()
        flash("Movie deleted from the list!", "success")
    else:
        flash("Movie not found in the list!", "danger")
    return redirect(url_for("main.view_list", list_id=list_id))

main/templates/home.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Home</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
  <style>
    body {
      background-color: #f0f5f9;
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      color: black;
      overflow-y: scroll;
      /* Allow vertical scrollbar */
    }

    body.dark-mode {
      background-color: #1a355b;
      color: #ffffff;
      /* Set text color to white in dark mode */
    }


    h1 {
      font-size: 2.5rem;
      font-family: "Acme", sans-serif;
      font-weight: 400;
      font-style: normal;
      text-align: center;
      margin-top: 50px;
      color: black;
    }

    body.dark-mode h1 {
      color: #ffffff;
    }

    h2 {
      font-family: "Acme", sans-serif;
      font-weight: 400;
      font-style: normal;
      font-size: 2rem;
    }

    body.dark-mode h2 {
      color: #000000;
    }

    .container {
      display: flex;
      justify-content: space-between;
      padding: 20px;
    }

    .left-column {
      flex: 1;
      background-color: #ffffff;
      /* White background */
      padding: 20px;
    }

    .left-column.dark-mode {
      background-color: #3a3a3a;
      color: #ffffff;
    }

    .right-column {
      flex: 1;
      background-color: #ffffff;
      /* White background */
      padding: 20px;
      border-left: 2px solid #ccc;
      /* Partition line */
    }

    .right-column.dark-mode {
      background-color: #3a3a3a;
      color: #ffffff;
    }

    form {
      margin-top: 20px;
    }

    form input[type="text"] {
      width: 60%;
      padding: 10px;
      margin-bottom: 10px;
    }

    /* Button styles
    .cssbuttons-io {
      position: relative;
      font-family: inherit;
      font-weight: 600;
      font-size: 17px;
      border-radius: 0.8em;
      cursor: pointer;
      border: none;
      background: linear-gradient(to right, #143d65, #5e84ab);
      color: ghostwhite;
      overflow: hidden;
      box-shadow: none;
    }

    .cssbuttons-io svg {
      width: 1.2em;
      height: 1.2em;
      margin-left: -0.9em;
      stroke-width: 2px;
    }

    .cssbuttons-io span {
      position: relative;
      z-index: 10;
      transition: color 0.4s;
      display: inline-flex;
      align-items: center;
      padding: 0.8em 0.9em 0.8em 1.02em;
    }

    .cssbuttons-io::before,
    .cssbuttons-io::after {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: 0;
    }

    .cssbuttons-io::before {
      content: "";
      background: #1a355b;
      width: 120%;
      left: -10%;
      transform: skew(30deg);
      transition: transform 0.4s cubic-bezier(0.3, 1, 0.8, 1);
    }

    .cssbuttons-io:hover::before {
      transform: translate3d(100%, 0, 0);
    }

    .cssbuttons-io:active {
      transform: scale(0.95);
    } */

    .swiper {
      padding: 50px;
      width: 50%;
      height: 50%;
    }

    .swiper-slide {
      text-align: center;
      font-size: 18px;
      background: white;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 300px;
      margin-bottom: 2em;
      border-radius: 10px;
    }

    .swiper-slide img {
      display: block;
      object-fit: fill;
      width: 100%;
      height: 100%;
      border-radius: 10px;
    }

    footer {
      background-color: #1a355b;
      color: #ffffff;
      text-align: center;
      padding: 10px 0;
      /* position: fixed; */
      bottom: 0;
      width: 100%;
      height: 30px;
      /* position: fixed; */
      z-index: 9;
    }

    footer.dark-mode {
      background-color: #1a252f;
    }

    /* Toggle switch styles */
    .toggle-switch {
      position: relative;
      display: inline-block;
      width: 60px;
      height: 34px;
      top: -10px;
    }

    .toggle-switch input {
      opacity: 0;
      width: 0;
      height: 0;
    }

    .slider {
      position: absolute;
      cursor: pointer;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: #ccc;
      transition: .4s;
    }

    .slider:before {
      position: absolute;
      content: "";
      height: 26px;
      width: 26px;
      left: 4px;
      bottom: 4px;
      background-color: white;
      transition: .4s;
    }

    input:checked+.slider {
      background-color: #2196F3;
    }

    input:checked+.slider:before {
      transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
      border-radius: 34px;
    }

    .slider.round:before {
      border-radius: 50%;
    }

    .listCards {
      background-color: #ffffff;
      margin-bottom: 15px;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      transition: transform 0.2s;
      text-align: center;
      font-size: 1em;
    }

    a {
      text-decoration: none;
      color: inherit;
    }

    .listCards:hover {
      transform: translateY(-5px);
    }

    .dark-mode .listCards {
      background-color: #244667;
      color: #ffffff;
    }

    @media (min-width: 1024px) {
      .listCards {
        width: 40%;
        margin-left: auto;
        margin-right: auto;
      }
    }

    /* Card flip styles */
    .card {
      width: 100%;
      height: 100%;
      perspective: 1000px;
    }

    .card-inner {
      width: 100%;
      height: 100%;
      position: relative;
      transform-style: preserve-3d;
      transition: transform 0.999s;
    }

    .card:hover .card-inner {
      transform: rotatex(-180deg);
    }

    .card-front,
    .card-back {
      position: absolute;
      width: 100%;
      height: 100%;
      backface-visibility: hidden;
    }

    .card-front {
      background-color: #6A2C70;
      color: #fff;
      display: flex;
      align-items: center;
      border-radius: 10px;
      justify-content: center;
      font-size: 24px;
      transform: rotateY(0deg);
    }

    .card-back {
      background: linear-gradient(90deg, hsla(215, 56%, 23%, 1) 36%, hsla(58, 16%, 49%, 1) 100%);
      color: #fff;
      display: flex;
      align-items: center;
      border-radius: 10px;
      justify-content: center;
      font-size: 24px;
      transform: rotatex(180deg);
    }

    .card-back p {
      margin: 0.1em;
      font-size: 1em;
    }
  </style>
</head>

<body>
  <!-- <nav>
    <button class="cssbuttons-io">
      <span>
        <a href="{{ url_for('main.home') }}">Home
          <svg viewBox="0 3 19.7 19.7" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="homeIconTitle"
            class="home-icon">
            <title id="homeIconTitle">Home</title>
            <path d="M12 3l7 6-1 1-1-1V20h-4V14H9v6H5V9L4 10 3 9l9-6z" fill="white" />
          </svg>
        </a>
      </span>
    </button>
    <button class="cssbuttons-io">
      <span>
        <a href="{{ url_for('users.logout') }}">Logout
          <svg viewBox="0 2 19 20" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="loginIconTitle"
            class="login-icon">
            <title id="loginIconTitle">Login</title>
            <path fill="white"
              d="M10.09,15.59L13.67,12L10.09,8.41L11.5,7L16.5,12L11.5,17L10.09,15.59M19,3H5C3.89,3 3,3.89 3,5V19C3,20.11 3.89,21 5,21H19C20.11,21 21,20.11 21,19V5C21,3.89 20.11,3 19,3M19,19H5V5H19V19Z" />
          </svg>
        </a>
      </span>
    </button>
    <label class="toggle-switch">
      <input type="checkbox" id="mode-toggle">
      <span class="slider round"></span>
    </label>
  </nav> -->
  <h1 class="dark-mode">Welcome to the Movie Library</h1>
  <div class="container">
    <div class="left-column">
      <h2>Your Movie Lists</h2>
      <ul>
        {% for movie_list in lists %}
        <a href="{{ url_for('main.view_list', list_id=movie_list.id) }}">
          <li class="listCards">{{ movie_list.title }}</li>
        </a>
        {% endfor %}
      </ul>
    </div>
    <div class="right-column">
      <h2>Create New List</h2>
      <form action="{{ url_for('main.create_list') }}" method="POST">
        {{ form.title() }} <br>
        <!-- <input type="text" name="title" placeholder="New List Title"> -->
        <button type="submit" class="search_button"><span>Create List</span></button>
      </form>
    </div>
  </div>
  <div class="swiper mySwiper">
    <div class="swiper-wrapper">
      {% for slider_url, slider_text in movies_slides.items() %}
      <div class="swiper-slide">
        <div class="card">
          <div class="card-inner">
            <div class="card-front">
              <img src="{{ slider_url }}" alt="">
            </div>
            <div class="card-back">
              <p>{{ slider_text }}</p>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-pagination"></div> -->
  </div>

  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

  <script>
    var swiper = new Swiper(".mySwiper", {
      spaceBetween: 30,
      centeredSlides: true,
      autoplay: {
        delay: 6000,
        disableOnInteraction: false,
      },
      loop: true,
      pagination: {
        el: ".swiper-pagination",
        clickable: true,
      },
      navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },
    });
  </script>
  <script>
    document.addEventListener('DOMContentLoaded', (event) => {
      const toggleButton = document.getElementById('mode-toggle');
      const body = document.body;
      body.classList.add('dark-mode');
    });
  </script>
</body>

</html>
{% endblock %}

main/templates/movie_detail.html
{% extends "base.html" %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ detail.Title }}</title>
    <style>
        body {
            background: hsla(215, 56%, 23%, 1);

            background: linear-gradient(90deg, hsla(215, 56%, 23%, 1) 36%, hsla(58, 16%, 49%, 1) 100%);

            background: -moz-linear-gradient(90deg, hsla(215, 56%, 23%, 1) 36%, hsla(58, 16%, 49%, 1) 100%);

            background: -webkit-linear-gradient(90deg, hsla(215, 56%, 23%, 1) 36%, hsla(58, 16%, 49%, 1) 100%);

            filter: progid: DXImageTransform.Microsoft.gradient(startColorstr="#1A355B", endColorstr="#908F69", GradientType=1);
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            color: rgb(255, 253, 253);
            overflow-y: scroll;
        }

        /* 
        .header {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin: 20px 0;
            font-size: 4em;
        } */
        /* 
        .title {
            font-size: 2.5rem;
            margin-bottom: 20px;
        }

        .poster {
            max-width: 100%;
            height: auto;
            margin-bottom: 20px;
            border-radius: 0.2em;
        }

        .rating,
        .genre,
        .runtime,
        .director,
        .actors,
        .language,
        .country {
            margin: 5px 0;
        }

        .details {
            padding: 15px;
            font-size: larger;
            color: white;

        }

        .plot {
            margin-top: 20px;
        } */

        #movie_container {
            display: flex;
            flex-grow: 1;
            width: 100%;
            height: 70vh;
        }

        .movie_left {
            width: 33.33%;
            padding: 0 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }

        .movie_right {
            width: 66.66%;
            padding: 0 20px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: left;
            height: 100%;
            flex-grow: 1;
            font-size: 1.2em;
        }

        .title {
            text-align: center;
            font-size: 2.5rem;
            margin-top: 1em;
            font-weight: bold;
        }

        .poster {
            max-width: 100%;
            height: auto;
            margin-bottom: 20px;
            border-radius: 0.2em;
        }

        .rating,
        .genre,
        .runtime,
        .director,
        .actors,
        .language,
        .country {
            margin: 5px 0;
            font-size: inherit;
        }

        .details {
            padding: 15px;
            font-size: larger;
            color: white;
        }

        .plot {
            margin-top: 20px;
            max-width: 50vw;
        }
    </style>
</head>

<body>
    <p class="title">{{ detail.Title }}</p>

    <div id="movie_container">
        <div class="movie_left">
            <img class="poster" src="{{ detail.Poster }}" alt="{{ detail.Title }}">
        </div>
        <div class="movie_right">
            <div class="rating"><b>IMDb Rating:</b> {{ detail.imdbRating }}</div>
            <div class="genre"><b>Genre:</b> {{ detail.Genre }}</div>
            <div class="runtime"><b>Runtime:</b> {{ detail.Runtime }}</div>
            <div class="director"><b>Director:</b> {{ detail.Director }}</div>
            <div class="actors"><b>Actors:</b> {{ detail.Actors }}</div>
            <div class="language"><b>Language:</b> {{ detail.Language }}</div>
            <div class="country"><b>Country:</b> {{ detail.Country }}</div>
            <div class="plot"><strong>Plot:</strong> {{ detail.Plot }}</div>
        </div>
</body>

</html>

{% endblock %}

main/templates/movie_list.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    input[type="text"] {
        width: 500px;
        height: 1em;
        padding: 0.8em;
        font-size: 1.2em;
    }

    .list_movie_card {
        border: 1px solid #1a355b !important;
    }

    .list_movie_card,
    .search_results_movie_card {
        width: 250px;
        border: 1px solid #ddd;
        border-radius: 10px;
        padding: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .search_results_movies {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }

    .search_results_movie_card {
        flex: 0 0 calc(16.666% - 20px);
        /* Adjust the width as needed */
        /* 16.666% represents approximately 1/6th of the container width */
        margin: 10px;
        /* Adjust margin as needed */
        height: 300px;
    }


    /* Ensure footer is at bottom of the page */
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        /* Ensure body takes up at least the full viewport height */
        margin: 0;
        padding: 0;
    }

    #movie_list_container {
        flex: 1;
        /* Grow to fill remaining space */
    }

    footer {
        background-color: #1a355b;
        color: #ffffff;
        text-align: center;
        padding: 10px 0;
        width: 100%;
    }

    a {
        text-decoration: none;
        /* Remove text decoration */
        color: white;
        /* Set button text color */
    }

    h1 {
        font-size: 4rem;
    }

    h2 {
        font-size: 2rem;
    }
</style>

<body>
    <div id="movie_list_container">
        <h1>{{ list.title.title() }}</h1>
        <p>Created On : {{ list.date_created.strftime("%Y-%m-%d") }}</p>
        <div>
            <form action="{{ url_for('main.search', list_id=list.id, page=1) }}" method="POST">
                <input type="text" name="query" placeholder="Search for movies" value="{{ prev_query|default('') }}">
                <button type="submit" class="search_button">Search</button>
            </form>
        </div>
        <h2>Movies in this list</h2>
        <div class="list_movies">
            {% if list.movies %}
            {% for movie in list.movies %}
            <div class="list_movie_card">
                <h3>{{ movie.title }}</h3>
                <p>{{ movie.year }}</p>
                <a href="{{ url_for('main.movie_detail', imdb_id=movie.imdb_id) }}">
                    <button class="search_button excess_button">
                        Open
                    </button>
                </a>
                <a href="{{ url_for('main.delete_movie', imdb_id=movie.imdb_id, list_id=list.id) }}">
                    <button class="search_button excess_button">
                        Delete
                    </button>
                </a>
            </div>
            {% endfor %}
            {% else %}
            <p>List is empty</p>
            {% endif %}
        </div>
        <h2>Search Results</h2>
        <div class="search_results_movies">
            {% if movies %}
            {% for movie in movies %}
            <div class="search_results_movie_card">
                <img src="{{ movie.Poster }}" alt="{{ movie.Title }}">
                <h4>{{ movie.Title }}</h4>
                <p>{{ movie.Year }}</p>
                <form action="{{ url_for('main.add_movie') }}" method="POST">
                    <input type="hidden" name="page" value="{{ curr_page|default(1) }}">
                    <input type="hidden" name="query" value="{{ prev_query|default('') }}">
                    <input type="hidden" name="title" value="{{ movie.Title }}">
                    <input type="hidden" name="year" value="{{ movie.Year }}">
                    <input type="hidden" name="imdb_id" value="{{ movie.imdbID }}">
                    <input type="hidden" name="list_id" value="{{ list.id }}">
                    <button type="submit" class="search_button excess_button">Add to List</button>
                </form>
            </div>
            {% endfor %}
        </div>
        <form action="{{ url_for('main.search', list_id=list.id, page=curr_page|default(1)|int + 1) }}" method="POST">
            <button type="submit" class="search_button excess_button">Show More</button>
            <input type="hidden" name="query" value="{{ prev_query|default('') }}">
        </form>
        {% else %}
        <p>No search results</p>
        {% endif %}
    </div>
</body>

</html>
{% endblock %}